class_name EdictData
extends RefCounted

## Twelve Edicts per Age, drafted three at a time. Eighteen picks in a run,
## so most of this is never seen — which is the point.
##
## `m` is merged into the player's modifier bag; `once` names a one-off hook.

const LIST := [
# ---------------------------------------------------------------- Dawn ----
[
 {"id": "firstfires", "name": "First Fires", "m": {"p_prod": 1},
  "desc": "+1 production in every city.",
  "flavour": "Warmth first. Everything else is negotiable."},
 {"id": "foraging", "name": "Foraging Rites", "m": {"t_food_wood": 1},
  "desc": "+1 food from every Forest and Jungle you work.",
  "flavour": "The wood feeds those who ask it politely."},
 {"id": "knapping", "name": "Stone Knapping", "m": {"s_melee": 5},
  "desc": "Melee units +5 strength.",
  "flavour": "A sharper edge is the oldest argument."},
 {"id": "slings", "name": "Slings and Stones", "m": {"s_ranged": 5},
  "desc": "Ranged units +5 strength.",
  "flavour": "The giant never hears the small stone coming."},
 {"id": "wander", "name": "Wanderlust", "m": {"mv_settler": 1, "settler_pct": -0.25},
  "desc": "Settlers move +1 and cost a quarter less.",
  "flavour": "Over that hill, they say, the grass is greener still."},
 {"id": "ancestral", "name": "Ancestral Mound", "m": {"cap_sci": 3},
  "desc": "+3 progress in your capital.",
  "flavour": "The dead are consulted. They are rarely wrong and never brief."},
 {"id": "trails", "name": "Trail Cutting", "m": {"mv_border": 1},
  "desc": "+1 movement inside your own borders.",
  "flavour": "A path is only a rumour walked often enough."},
 {"id": "clanties", "name": "Clan Ties", "m": {"city_cap": 1},
  "desc": "+1 to your city limit.",
  "flavour": "Cousins, all of them. Somehow."},
 {"id": "salt", "name": "Salt Trade", "m": {"p_gold": 2},
  "desc": "+2 gold in every city.",
  "flavour": "White, common, and worth more than silver to a hungry road."},
 {"id": "watchfires", "name": "Watchfires", "m": {"city_hp": 35, "city_str": 5},
  "desc": "Cities +35 defence and +5 strength.",
  "flavour": "Someone must stay awake. Tonight it is you."},
 {"id": "hunters", "name": "Hunters' Pact", "m": {"t_food_res": 1, "kill_gold": 15},
  "desc": "+1 food from bonus resources; +15 gold for each unit you destroy.",
  "flavour": "Take what you need. Leave the rest to breed."},
 {"id": "cairns", "name": "Cairn Markers", "m": {"sight_all": 1, "p_gold": 1},
  "desc": "All units see one tile further; +1 gold in every city.",
  "flavour": "Stones piled by strangers, for strangers."},
],
# -------------------------------------------------------------- Bronze ----
[
 {"id": "casting", "name": "Bronze Casting", "m": {"s_melee": 8},
  "desc": "Melee units +8 strength.",
  "flavour": "Copper is soft. Tin is soft. Together they take an edge."},
 {"id": "ditches", "name": "Irrigation Ditches", "m": {"t_food_river": 1, "p_food": 1},
  "desc": "+1 food from river tiles, and +1 food in every city.",
  "flavour": "The flood, taught manners."},
 {"id": "terrace", "name": "Terracing", "m": {"t_food_hill": 1},
  "desc": "+1 food from every Hills tile you work.",
  "flavour": "Steps cut for grain, climbed by everything else."},
 {"id": "ziggurat", "name": "Ziggurats", "m": {"p_sci": 2},
  "desc": "+2 progress in every city.",
  "flavour": "Build upward until the sky takes an interest."},
 {"id": "caravan", "name": "Caravanserai", "m": {"p_gold": 3},
  "desc": "+3 gold in every city.",
  "flavour": "Water, shade, and a fee. In that order."},
 {"id": "phalanx", "name": "Phalanx Drill", "m": {"pct_home": 0.25},
  "desc": "+25% strength defending inside your borders.",
  "flavour": "One shield is a shield. Forty is a wall."},
 {"id": "written", "name": "The Written Word", "m": {"pct_sci": 0.20},
  "desc": "+20% progress.",
  "flavour": "A clerk records the barley. Civilisation follows the clerk."},
 {"id": "charioteers", "name": "Charioteers", "m": {"mv_mounted": 1, "ignore_zoc": 1},
  "desc": "Mounted units +1 movement and ignore enemy zones of control.",
  "flavour": "Too fast to block, too proud to stop."},
 {"id": "charter", "name": "Colonial Charter", "m": {"city_cap": 1, "pop_start": 1},
  "desc": "+1 city limit; new cities begin at size 2.",
  "flavour": "Signed, sealed, and sent somewhere inconvenient."},
 {"id": "claygran", "name": "Granaries of Clay", "m": {"p_food": 2},
  "desc": "+2 food in every city.",
  "flavour": "A full jar is a year you get to choose."},
 {"id": "levy", "name": "The Levy", "m": {"unit_pct": -0.25},
  "desc": "Units cost a quarter less.",
  "flavour": "Every third man. Bring your own shoes."},
 {"id": "ledger", "name": "The Bronze Ledger", "m": {"struct_pct": -0.25},
  "desc": "Structures cost a quarter less.",
  "flavour": "What is measured is owed."},
],
# ---------------------------------------------------------------- Iron ----
[
 {"id": "discipline", "name": "Legionary Discipline", "m": {"s_melee": 12, "heal_win": 25},
  "desc": "Melee +12 strength, and they heal after winning.",
  "flavour": "Dig the ditch. Then dig it again, properly."},
 {"id": "siegecraft", "name": "Siegecraft", "m": {"pct_vs_city": 0.5, "rng_siege": 1},
  "desc": "Siege units +50% against cities and +1 range.",
  "flavour": "Walls are a schedule, not an obstacle."},
 {"id": "aqueducts", "name": "Aqueducts", "m": {"p_food": 3, "max_pop": 8},
  "desc": "+3 food everywhere; cities may grow past 8.",
  "flavour": "Water arrives on time. The empire notices."},
 {"id": "academies", "name": "Academies", "m": {"pct_sci": 0.25, "cap_sci": 5},
  "desc": "+25% progress, and +5 more in your capital.",
  "flavour": "Argument, but with seating."},
 {"id": "coinage", "name": "Coinage", "m": {"pct_gold": 0.30},
  "desc": "+30% gold.",
  "flavour": "A face on a disc, and suddenly everyone agrees on value."},
 {"id": "roads", "name": "The Great Roads", "m": {"mv_border": 2, "p_gold": 2},
  "desc": "+2 movement inside your borders; +2 gold in every city.",
  "flavour": "Built for legions. Used, mostly, by merchants."},
 {"id": "feudal", "name": "Feudal Levy", "m": {"upkeep_free": 2},
  "desc": "Two more units supported free per city.",
  "flavour": "Land for loyalty. The oldest exchange rate."},
 {"id": "stirrups", "name": "Stirrups", "m": {"s_mounted": 14},
  "desc": "Mounted units +14 strength.",
  "flavour": "Two loops of leather rewrote the century."},
 {"id": "guilds", "name": "Guilds", "m": {"pct_prod": 0.25},
  "desc": "+25% production.",
  "flavour": "Seven years an apprentice, and worth every hour."},
 {"id": "codex", "name": "Codex of Law", "m": {"diplo": 18, "no_tribute": 1},
  "desc": "Every rival warms to you, and none may demand tribute of you.",
  "flavour": "Written down, so it can be argued about precisely."},
 {"id": "ambition", "name": "Imperial Ambition", "m": {"city_cap": 1, "keep_structs": 1},
  "desc": "+1 city limit; captured cities keep what they have built.",
  "flavour": "The map has edges. They are a suggestion."},
 {"id": "crossbows", "name": "Crossbow Corps", "m": {"s_ranged": 12, "rng_ranged": 1},
  "desc": "Ranged units +12 strength and +1 range.",
  "flavour": "A year to train an archer. An afternoon to train this."},
],
# ---------------------------------------------------------------- Sail ----
[
 {"id": "caravel", "name": "Caravels", "m": {"embark": 1},
  "desc": "Your land units may cross water.",
  "flavour": "The sea stops being a wall and becomes a road."},
 {"id": "gunpowder", "name": "Gunpowder Mills", "m": {"s_gp": 14, "free_niter": 1},
  "desc": "Gunpowder units +14 strength, and need no Niter.",
  "flavour": "Loud, filthy, and the end of the knight."},
 {"id": "astronomy", "name": "Astronomy", "m": {"pct_sci": 0.30}, "once": "reveal",
  "desc": "+30% progress, and the whole map is charted.",
  "flavour": "Look up long enough and the world gets smaller."},
 {"id": "fleet", "name": "Mercantile Fleet", "m": {"p_gold": 5, "t_gold_water": 1},
  "desc": "+5 gold in every city; +1 gold on every water tile.",
  "flavour": "A hold full of pepper is worth a hold full of soldiers."},
 {"id": "press", "name": "The Printing Press", "m": {"sci_per_pop": 1},
  "desc": "+1 progress for every point of population you hold.",
  "flavour": "Now the arguments travel faster than the armies."},
 {"id": "bastion", "name": "Bastions", "m": {"city_hp": 90, "city_str": 12},
  "desc": "Cities +90 defence and +12 strength.",
  "flavour": "Angles, not height. Let the cannon look foolish."},
 {"id": "standing", "name": "Standing Army", "m": {"upkeep_pct": -0.5, "xp_start": 25},
  "desc": "Upkeep halved; new units begin trained.",
  "flavour": "Paid in peacetime, which is the whole trick."},
 {"id": "colonies", "name": "Colonisation", "m": {"city_cap": 2, "settler_no_pop": 1},
  "desc": "+2 city limit; Settlers no longer cost population.",
  "flavour": "Somewhere out there is a bay with your name on it."},
 {"id": "survey", "name": "The Grand Survey", "m": {"city_radius": 1},
  "desc": "Every city works one ring further out.",
  "flavour": "Chains, theodolites, and a great deal of arguing about hedges."},
 {"id": "companies", "name": "Chartered Companies", "m": {"pct_gold": 0.40, "buy_pct": -0.30},
  "desc": "+40% gold; buying costs a third less.",
  "flavour": "A flag, a fleet, and a shareholder meeting."},
 {"id": "corps", "name": "Diplomatic Corps", "m": {"diplo": 28, "tribute_up": 1},
  "desc": "Rivals warm to you greatly; your demands cost no goodwill.",
  "flavour": "Lying abroad for the good of the country."},
 {"id": "drill", "name": "Drill Yards", "m": {"mv_all": 1},
  "desc": "All units +1 movement.",
  "flavour": "March, halt, march. Until the marching thinks for itself."},
],
# --------------------------------------------------------------- Steam ----
[
 {"id": "steam", "name": "Steam Engines", "m": {"pct_prod": 0.35},
  "desc": "+35% production.",
  "flavour": "Fire, water, and a piston. The rest is bookkeeping."},
 {"id": "railnet", "name": "Rail Network", "m": {"mv_border": 3, "p_gold": 4},
  "desc": "+3 movement inside your borders; +4 gold in every city.",
  "flavour": "The timetable invents the minute."},
 {"id": "rifling", "name": "Rifling", "m": {"s_melee": 16},
  "desc": "Melee units +16 strength.",
  "flavour": "A groove in a barrel, and the range triples."},
 {"id": "trains", "name": "Artillery Trains", "m": {"s_siege": 16, "rng_siege": 1},
  "desc": "Siege units +16 strength and +1 range.",
  "flavour": "Guns too heavy to move, moved anyway."},
 {"id": "schools", "name": "Public Schools", "m": {"pct_sci": 0.40},
  "desc": "+40% progress.",
  "flavour": "Literacy, delivered whether wanted or not."},
 {"id": "sanitation", "name": "Sanitation", "m": {"p_food": 4},
  "desc": "+4 food in every city.",
  "flavour": "The century's greatest invention smells faintly of chlorine."},
 {"id": "indlevy", "name": "Industrial Levy", "m": {"unit_pct": -0.35},
  "desc": "Units cost a third less.",
  "flavour": "Interchangeable parts, interchangeable men."},
 {"id": "totalwar", "name": "Total War", "m": {"pct_war": 0.20, "kill_gold": 40},
  "desc": "+20% strength in battle; +40 gold for each unit destroyed.",
  "flavour": "The whole nation is the army now. Nobody voted for this."},
 {"id": "centralbank", "name": "Central Bank", "m": {"pct_gold": 0.50},
  "desc": "+50% gold.",
  "flavour": "Someone must be trusted with the printing. Reluctantly, us."},
 {"id": "conscript", "name": "Conscription", "m": {"upkeep_free": 3, "xp_start": 50},
  "desc": "Three more units free per city; new units arrive veteran.",
  "flavour": "Your number, sir. It has come up."},
 {"id": "telegraph", "name": "The Telegraph", "m": {"pct_sci": 0.15, "sight_all": 1}, "once": "spy",
  "desc": "+15% progress, +1 sight, and every rival city is revealed.",
  "flavour": "The world shrinks to the length of a wire."},
 {"id": "expanse", "name": "Imperial Expanse", "m": {"city_cap": 2, "city_radius": 1},
  "desc": "+2 city limit; every city works one ring further out.",
  "flavour": "The sun, famously, declines to set on it."},
],
# -------------------------------------------------------------- Atomic ----
[
 {"id": "assembly", "name": "Assembly Lines", "m": {"pct_prod": 0.50},
  "desc": "+50% production.",
  "flavour": "Any colour you like."},
 {"id": "mech", "name": "Mechanised Corps", "m": {"mv_all": 1, "s_all": 10},
  "desc": "All units +1 movement and +10 strength.",
  "flavour": "The horse retires with honours."},
 {"id": "labs", "name": "Research Labs", "m": {"pct_sci": 0.60},
  "desc": "+60% progress.",
  "flavour": "Funding, whiteboards, and the occasional catastrophe."},
 {"id": "markets", "name": "Global Markets", "m": {"pct_gold": 0.70},
  "desc": "+70% gold.",
  "flavour": "Everything, everywhere, priced by lunchtime."},
 {"id": "fertiliser", "name": "Fertiliser", "m": {"p_food": 6},
  "desc": "+6 food in every city.",
  "flavour": "Bread out of air. Nobody quite believes it yet."},
 {"id": "deterrence", "name": "Deterrence", "m": {"city_hp": 160, "city_str": 20, "diplo": 30},
  "desc": "Cities +160 defence and +20 strength; every rival grows careful.",
  "flavour": "The safest weapon is the one nobody dares use."},
 {"id": "atomic", "name": "Atomic Theory", "m": {"beacon_pct": -0.30}, "once": "uranium",
  "desc": "Uranium is revealed everywhere; The Beacon costs a third less.",
  "flavour": "A very small thing, split, at very great expense."},
 {"id": "airsup", "name": "Air Superiority", "m": {"s_ranged": 22, "rng_ranged": 1},
  "desc": "Ranged units +22 strength and +1 range.",
  "flavour": "Whoever owns the sky is merely renting the ground."},
 {"id": "blitz", "name": "Blitz", "m": {"move_after": 1, "s_mounted": 14},
  "desc": "Mounted units +14 strength and may move after attacking.",
  "flavour": "Speed is a weapon in its own right."},
 {"id": "massprod", "name": "Mass Production", "m": {"unit_pct": -0.50, "struct_pct": -0.40},
  "desc": "Units cost half; structures a good deal less.",
  "flavour": "Cheaper by the thousand, and there are thousands."},
 {"id": "space", "name": "Space Program", "m": {"pct_sci": 0.25, "p_sci": 8},
  "desc": "+25% progress and +8 progress in every city.",
  "flavour": "We went, mostly, to look back at ourselves."},
 {"id": "pax", "name": "Pax Machina", "m": {"diplo": 50, "p_gold": 10}, "once": "endwars",
  "desc": "Every war ends at once; rivals warm greatly; +10 gold in every city.",
  "flavour": "Peace, arranged by machines that never wanted anything else."},
],
]


## The six leaders. You are offered three at the start of a run.
const LEADERS := [
 {"id": "ashur", "name": "Ashur", "civ": "Assyria", "adj": "Assyrian", "colour": "crimson",
  "trait": "The Lion Hunt",
  "trait_desc": "Units heal 40 when they destroy an enemy, and hit 15% harder attacking.",
  "m": {"heal_win": 40, "pct_atk": 0.15}, "unique": "siegetower", "agenda": "conqueror",
  "agenda_desc": "Preys on the weak. Respects a large army and nothing else.",
  "cities": ["Ashur","Nineveh","Kalhu","Dur-Sharrukin","Arbela","Harran","Tarbisu","Imgur-Enlil"]},

 {"id": "nefertiti", "name": "Nefertiti", "civ": "Kemet", "adj": "Kemetite", "colour": "amber",
  "trait": "Gift of the River",
  "trait_desc": "River and floodplain tiles give +1 food. Wonders build 40% faster.",
  "m": {"t_food_river": 1, "wonder_pct": -0.40}, "unique": "chariot", "agenda": "builder",
  "agenda_desc": "Measures rivals by their monuments, and resents a rival wonder.",
  "cities": ["Waset","Men-nefer","Abdju","Iunu","Nekhen","Akhetaten","Swenett","Djedu"]},

 {"id": "ragnhild", "name": "Ragnhild", "civ": "the Norse", "adj": "Norse", "colour": "indigo",
  "trait": "Sea Wolves",
  "trait_desc": "Crosses water from the Bronze Age. Water tiles give +1 production. +25% attacking cities.",
  "m": {"early_embark": 1, "t_prod_water": 1, "pct_vs_city": 0.25}, "unique": "berserker",
  "agenda": "raider", "agenda_desc": "Raids the wealthy, and grows restless in a long peace.",
  "cities": ["Uppsala","Hedeby","Kaupang","Birka","Ribe","Trondheim","Jorvik","Lindholm"]},

 {"id": "chandragupta", "name": "Chandragupta", "civ": "Maurya", "adj": "Mauryan", "colour": "olive",
  "trait": "Dharma",
  "trait_desc": "+2 food and +1 progress in every city. Rivals begin considerably friendlier.",
  "m": {"p_food": 2, "p_sci": 1, "diplo": 20}, "unique": "elephant", "agenda": "peaceful",
  "agenda_desc": "Loathes warmongers. Rewards a long, quiet peace.",
  "cities": ["Pataliputra","Ujjain","Taxila","Kaushambi","Vidisha","Suvarnagiri","Tosali","Rajagriha"]},

 {"id": "wuzhao", "name": "Wu Zhao", "civ": "Tang", "adj": "Tang", "colour": "teal",
  "trait": "Mandate of Heaven",
  "trait_desc": "+30% progress in your capital. Structures cost a quarter less.",
  "m": {"cap_sci_pct": 0.30, "struct_pct": -0.25}, "unique": "chukonu", "agenda": "scholar",
  "agenda_desc": "Watches the Ages. Disdains the backward and envies the advanced.",
  "cities": ["Chang'an","Luoyang","Yangzhou","Chengdu","Guangzhou","Taiyuan","Kaifeng","Jiangling"]},

 {"id": "moctezuma", "name": "Moctezuma", "civ": "the Mexica", "adj": "Mexica", "colour": "plum",
  "trait": "Flower War",
  "trait_desc": "Destroying a unit brings 25 gold and 10 progress. +1 city limit.",
  "m": {"kill_gold": 25, "kill_sci": 10, "city_cap": 1}, "unique": "eagle", "agenda": "tributary",
  "agenda_desc": "Demands tribute often, and remembers who paid.",
  "cities": ["Tenochtitlan","Texcoco","Tlacopan","Xochimilco","Culhuacan","Azcapotzalco","Tlatelolco","Chalco"]},
]


const DIFFICULTIES := [
	{"name": "Wanderer", "ai": 0.85, "barb": 0.6, "aggression": 0.6,
	 "desc": "A forgiving world. Rivals expand slowly and rarely strike first."},
	{"name": "Chieftain", "ai": 1.0, "barb": 1.0, "aggression": 1.0,
	 "desc": "A fair contest. Rivals play as you do, and punish a weak border."},
	{"name": "Conqueror", "ai": 1.35, "barb": 1.5, "aggression": 1.5,
	 "desc": "A hard world. Rivals grow faster, scheme sooner, and finish what they start."},
]
